"""Builtin cleanup rule packs.

Each rule describes a *category* of junk: where to look (scope), what glob
patterns count as a match, and safety metadata (risk level, whether it's
enabled by default). Rules never see file contents — only paths, sizes, and
modification times.
"""

from __future__ import annotations

from filecleaner.models import Rule

BUILTIN_RULES: tuple[Rule, ...] = (
    Rule(
        id="system_caches",
        label="Application caches",
        category="Caches",
        description="~/Library/Caches/* — regenerable per-app caches",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=("Library/Caches/*",),
        min_age_days=3,
    ),
    Rule(
        id="logs",
        label="User logs",
        category="Logs",
        description="~/Library/Logs/* — application log files",
        enabled_by_default=True,
        risk="low",
        kind="file",
        scope="home",
        include_globs=("Library/Logs/**/*",),
        min_age_days=7,
    ),
    Rule(
        id="crash_reports",
        label="Crash & diagnostic reports",
        category="Logs",
        description="~/Library/Logs/DiagnosticReports/* — crash logs",
        enabled_by_default=True,
        risk="low",
        kind="file",
        scope="home",
        include_globs=("Library/Logs/DiagnosticReports/*",),
        min_age_days=0,
    ),
    Rule(
        id="trash",
        label="Trash",
        category="Trash",
        description="~/.Trash/* — already user-deleted files",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=(".Trash/*",),
        min_age_days=0,
    ),
    Rule(
        id="ds_store",
        label=".DS_Store / thumbnail junk",
        category="System junk",
        description="Finder metadata files scattered across the home directory",
        enabled_by_default=True,
        risk="low",
        kind="file",
        scope="home",
        include_globs=("**/.DS_Store",),
        exclude_globs=("Library/**",),
        min_age_days=0,
    ),
    Rule(
        id="browser_caches",
        label="Browser caches",
        category="Caches",
        description="Safari / Chrome / Firefox / Edge on-disk HTTP caches",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=(
            "Library/Caches/com.apple.Safari/*",
            "Library/Caches/Google/Chrome/*",
            "Library/Application Support/Google/Chrome/*/Cache",
            "Library/Application Support/Google/Chrome/*/Code Cache",
            "Library/Caches/Firefox/*",
            "Library/Application Support/Firefox/Profiles/*/cache2",
            "Library/Caches/com.microsoft.edgemac/*",
        ),
        min_age_days=1,
    ),
    Rule(
        id="dev_xcode",
        label="Xcode DerivedData",
        category="Developer",
        description="~/Library/Developer/Xcode/DerivedData — fully regenerated on next build",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=("Library/Developer/Xcode/DerivedData/*",),
        min_age_days=3,
    ),
    Rule(
        id="dev_xcode_archives",
        label="Xcode old device support / archives cache",
        category="Developer",
        description="~/Library/Developer/Xcode/iOS DeviceSupport and CoreSimulator caches",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=(
            "Library/Developer/CoreSimulator/Caches/*",
        ),
        min_age_days=7,
    ),
    Rule(
        id="dev_npm_cache",
        label="npm/yarn/pnpm package caches",
        category="Developer",
        description="Global JS package manager caches — re-downloadable",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=(
            ".npm/_cacache/*",
            "Library/Caches/Yarn/*",
            "Library/pnpm/store/*",
            ".cache/yarn/*",
        ),
        min_age_days=3,
    ),
    Rule(
        id="dev_pip_cache",
        label="pip / conda package caches",
        category="Developer",
        description="Python package manager caches — re-downloadable",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=(
            "Library/Caches/pip/*",
            ".cache/pip/*",
        ),
        min_age_days=3,
    ),
    Rule(
        id="dev_homebrew_cache",
        label="Homebrew download cache",
        category="Developer",
        description="~/Library/Caches/Homebrew — downloaded bottles/archives, kept after install",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="home",
        include_globs=("Library/Caches/Homebrew/*",),
        min_age_days=3,
    ),
    Rule(
        id="dev_docker_reclaimable",
        label="Docker Desktop VM disk image slack",
        category="Developer",
        description="Docker Desktop cache/log data under Library/Containers — NOT images/volumes "
        "(use `docker system df` / `docker system prune` for those, since they need Docker's own "
        "bookkeeping to remove safely)",
        enabled_by_default=False,
        risk="medium",
        kind="dir",
        scope="home",
        include_globs=("Library/Containers/com.docker.docker/Data/log/*",),
        min_age_days=7,
    ),
    Rule(
        id="dev_node_modules",
        label="Old node_modules directories",
        category="Developer (opt-in)",
        description="node_modules folders not modified recently — regenerable via package "
        "manager install, but off by default since a project might still be in active use",
        enabled_by_default=False,
        risk="medium",
        kind="dir",
        scope="home",
        include_globs=("**/node_modules",),
        exclude_globs=("Library/**",),
        min_age_days=30,
    ),
    Rule(
        id="external_trash",
        label="External drive Trash",
        category="Trash",
        description="Per-user Trash folders on external/removable volumes",
        enabled_by_default=True,
        risk="low",
        kind="dir",
        scope="each_volume",
        include_globs=(".Trashes/*",),
        min_age_days=0,
    ),
    Rule(
        id="old_downloads",
        label="Old files in Downloads",
        category="Personal (opt-in)",
        description="Files in ~/Downloads untouched for a long time — off by default, these are "
        "personal files, not junk",
        enabled_by_default=False,
        risk="medium",
        kind="file",
        scope="home",
        include_globs=("Downloads/*",),
        min_age_days=90,
    ),
)


def rules_by_id() -> dict[str, Rule]:
    return {r.id: r for r in BUILTIN_RULES}
